const express = require('express');
const crypto = require('crypto');

// ─────────────────────────────────────────────
// Backend Identity & Port from CLI arguments
// Usage:  node server.js A 3001
//         node server.js B 3002
// ─────────────────────────────────────────────

const BACKEND_ID = process.argv[2] || 'A';
const PORT = parseInt(process.argv[3], 10) || 3001;

const app = express();

// ─────────────────────────────────────────────
// Middleware: Attach X-Backend header to every response
// ─────────────────────────────────────────────

app.use((req, res, next) => {
  res.setHeader('X-Backend', BACKEND_ID);
  next();
});

// ─────────────────────────────────────────────
// GET /api/status
// Returns the service status and backend identity.
// Used by nginx health checks and load balancing verification.
// ─────────────────────────────────────────────

app.get('/api/status', (req, res) => {
  res.json({
    service: 'running',
    backend: BACKEND_ID,
  });
});

// ─────────────────────────────────────────────
// GET /api/cached
// Returns a cacheable response with:
//   Cache-Control: max-age=60
//   ETag: (auto-generated by Express)
//
// Supports conditional requests:
//   If-None-Match → 304 Not Modified
// ─────────────────────────────────────────────

app.get('/api/cached', (req, res) => {
  res.set('Cache-Control', 'max-age=60');
  res.json({
    service: 'running',
    backend: BACKEND_ID,
  });
});

// ─────────────────────────────────────────────
// Start server
// ─────────────────────────────────────────────

app.listen(PORT, () => {
  console.log(`Backend ${BACKEND_ID} listening on port ${PORT}`);
});
